# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Deployment for pyrios
# See https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyrios
  labels:
    app: pyrios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyrios
  template:
    metadata:
      labels:
        app: pyrios
    spec:
      containers:
      - name: pyrios
        image: us.gcr.io/not-my-project/pyrios-app:staging
        env:
        - name: ES_SERVER
          valueFrom:
            configMapKeyRef:
              name: esconfig
              key: ES_SERVER
        imagePullPolicy: Always
        ports:
        - containerPort: 9200
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9200
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9200
        resources:
          limits:
            cpu: 10m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 100Mi
